### ISSUE TITLE
undefined method `this`

### ISSUE THREAD

**Issue by adambedford** [plentz/lol_dba#82] opened 2017-03-10 02:14 UTC
I just installed the gem and ran `lol_dba db:find_indexes` and received this output:

```
/Users/Adam/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/rubygems/specification.rb:2158:in `method_missing': undefined method `this' for #<Gem::Specification:0x3fe09e0b3ce0 lol_dba-2.1.1> (NoMethodError)
	from /Users/Adam/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/rubygems/specification.rb:1057:in `find_active_stub_by_path'
	from /Users/Adam/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:64:in `require'
	from /Users/Adam/.rvm/gems/ruby-2.3.1/gems/lol_dba-2.1.1/bin/lol_dba:7:in `<top (required)>'
	from /Users/Adam/.rvm/gems/ruby-2.3.1/bin/lol_dba:23:in `load'
	from /Users/Adam/.rvm/gems/ruby-2.3.1/bin/lol_dba:23:in `<main>'
	from /Users/Adam/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `eval'
	from /Users/Adam/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `<main>'
```

Has anyone run into this before with Rails 5 and Ruby 2.3.1?

**Comment by plentz** [comment] 2017-03-13 16:35
@adambedford sorry for taking so long to reply. probably related with some recent changes @ rubygems. I will look at it later today

**Comment by plentz** [comment] 2017-04-12 14:15
@adambedford I've just tested using ruby 2.4.1 and the last version of lol_dba and the message didn't show up. Can you test it using the last version?

**Comment by sfsgagi** [comment] 2017-05-15 20:48
I am on Rails 4.2 and Ruby 2.3.4 and was getting the same error when I initially tried the simple:
```
gem install lol_dba
lol_dba db:find_indexes
```
I was able to resolve it by adding the gem to Gemfile (development group) and then after `bundle`, it worked ok. I am using RVM in case it matters.

**Comment by plentz** [comment] 2017-07-04 14:14
Closing it since it looks like the problem isn't with lol_dba itself

**Closed** 2017-07-04 14:14 UTC
Labels: bug, waiting feedback
